export const linhas = [
  {
    id: '0',
    codigo: '0.108',
    origem: 'Taguatinga Centro',
    destino: 'Plano Piloto',
    onibus: 12,
    passageiros: 1850,
    tempoMedio: 48,
    atrasos: 12,
    ocupacao: 78,
    arrecadacao: 9250,
  },
  {
    id: '1',
    codigo: '0.110',
    origem: 'Ceilândia',
    destino: 'Plano Piloto',
    onibus: 15,
    passageiros: 2300,
    tempoMedio: 55,
    atrasos: 18,
    ocupacao: 84,
    arrecadacao: 11500,
  },
  {
    id: '2',
    codigo: '0.120',
    origem: 'Samambaia',
    destino: 'Plano Piloto',
    onibus: 10,
    passageiros: 1600,
    tempoMedio: 42,
    atrasos: 8,
    ocupacao: 72,
    arrecadacao: 8000,
  },
  {
    id: '3',
    codigo: '0.140',
    origem: 'Gama',
    destino: 'Plano Piloto',
    onibus: 9,
    passageiros: 1400,
    tempoMedio: 50,
    atrasos: 15,
    ocupacao: 69,
    arrecadacao: 7000,
  },
];